### PR TITLE
Add Notices

### PR DESCRIPTION
**Pull request by hapiben**
Acceptance Criteria
=================
- Flash notices are built in plug
- Flash notices display on schools dashboard when schools lending is blocked

Solution
=================
- Added new migration for notices
- Implement a method to render the notices

Checklist
=================

- [ ] [ ] Pull Request should have a descriptive title
- [ ] [ ] Code is understandable without Dev
- [ ] [ ] Acceptance criteria, what was changed, and why it was changed (If applicable) on Pull / Merge Request
- [ ] [ ] All new methods have a relevant spec

### CODE REVIEW

**Comment by ostigley** [comment]
giz a description bae

**Comment by hapiben** [comment]
*Acceptance Criteria:*

- Flash notices are built in plug
- Flash notices display on schools dashboard when schools lending is blocked

**Comment by hapiben** [comment]
@ostigley Description added.

**Comment by ostigley** [comment]
nice one @hapiben

**Review by richardmatthewsdev — APPROVED** [review]
Looks good, should this repo live on Gitlab? Or the digitalNZ github?

**Comment by hapiben** [comment]
@Reinkaos Plan is to have it opensource. 👍

**Comment by hapiben** [comment]
Thanks @ostigley @Reinkaos

**Pull request merged**
